- name: catalogue setup
  hosts: all
  become: yes
  vars:
    component: catalogue
  tasks:
    -name: NodeJS Setup
     ansible.builtin.import_tasks: nodejs.yaml
    # ansible.builtin.import_tasks: stuff.yaml