- name: rabbitmq setup
  hosts: all
  become: true
  tasks:
    - name: Install erlang Repos
      ansible.builtin.shell: -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

    - name: Install rabbitmq Repos
      ansible.builtin.shell: -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

    - name: Install Rabbitmq server
      ansible.builtin.yum:
        name: rabbitmq-server
        state: installed
    - name: start rabbitmq service
      ansible.builtin.systemd:
        name: rabbitmq-server
        state: restarted
        enable: yes

    - name: Add application user
      community.rabbitmq.rabbitmq_user:
        user: roboshop
        password: roboshop123
        vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        state: present



#log=/tmp/roboshop.log
#echo -e "\e[36m<<<< creating rabbitmq >>>>>\e[0m" | tee -a ${log}
#curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash &>>${log}
#curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash &>>${log}
#yum install rabbitmq-server -y &>>${log}
#systemctl enable rabbitmq-server &>>${log}
#systemctl start rabbitmq-server &>>${log}
#rabbitmqctl add_user roboshop roboshop123 &>>${log}
#rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*" &>>${log}